---
version: '3'
services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_TYPE: postgresql
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - no-internet
      - backbone
    labels: 
      - "traefik.enable=true"
      - "traefik.docker.network=backbone"
      - "traefik.http.routers.matamo.rule=Host(`analytics.aquiver.de`)"
      - "traefik.http.routers.matamo.entrypoints=websecure"
      - "traefik.http.routers.matamo.tls=true"
      - "traefik.http.routers.matamo.tls.certresolver=wildcard-godaddy"
      - "traefik.http.routers.matamo.service=matamo-service@docker"
      - "traefik.http.services.matamo-service.loadbalancer.server.port=3000"
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: umami
    env_file:
      - .env
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    restart: always
    networks:
      - no-internet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      
volumes:
  umami-db-data:

networks:
  no-internet:
    driver: bridge
    internal: true
  internet:
    driver: bridge
  backbone:
    external: true
