global:
  sendAnonymousUsage: false

api:
  dashboard: false
  insecure: false

providers:
  docker:
    watch: true
    exposedByDefault: false
log:
  level: DEBUG

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  websecure:
    address: ":443"

certificatesResolvers:
  wildcard-godaddy:
    acme:
      email: "<yourmail>"
      httpChallenge:
        entryPoint: web
#      dnsChallenge:
#        provider: godaddy
#        delayBeforeCheck: 0