version: "3"

services:
  db:
    image: mariadb:10.11
    command: --max-allowed-packet=64MB
    restart: always
    networks:
      - no-internet
    volumes:
      - db:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    env_file:
      - ./db.env

  app:
    image: matomo:fpm-alpine
    restart: always
    networks:
      - no-internet
    volumes:
      # - ./config:/var/www/html/config:z
      # - ./logs:/var/www/html/logs:z
      - matomo:/var/www/html:z
    environment:
      - MATOMO_DATABASE_HOST=db
      - PHP_MEMORY_LIMIT=2048M
    env_file:
      - ./db.env


  web:
    image: nginx:alpine
    restart: always
    networks:
      - no-internet
      - internet
      - backbone
    volumes:
      - matomo:/var/www/html:z,ro
      # see https://github.com/matomo-org/matomo-nginx
      - ./matomo.conf:/etc/nginx/conf.d/default.conf:z,ro
    labels: 
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_backbone"
      - "traefik.http.routers.matamo.rule=Host(`matamo.aquiver.de`)"
      - "traefik.http.routers.matamo.entrypoints=websecure"
      - "traefik.http.routers.matamo.tls=true"
      - "traefik.http.routers.matamo.tls.certresolver=wildcard-godaddy"
      - "traefik.http.routers.matamo.service=matamo-service@docker"
      - "traefik.http.services.matamo-service.loadbalancer.server.port=80"


networks:
  no-internet:
    driver: bridge
    internal: true
  internet:
    driver: bridge
  backbone:
#    name: traefik_backbone
    external: true
volumes:
  db:
  matomo:
